version: "3.9"
services:
  notebook:
    container_name: arachnid_jupyter
    build:
      context: .
      target: build
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - JUPYTER_TOKEN=sample
